//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectTest1.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Student
    {
        public int Id { get; set; }
        //[DisplayName("Naaaam")]
        public string Name { get; set; }
        public int Marks { get; set; }
        public string State { get; set; }
    }
}
