//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRecords.WebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/SchoolRecords.WebService")]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int MarksField;
        
        private string NameField;
        
        private string stateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Marks
        {
            get
            {
                return this.MarksField;
            }
            set
            {
                this.MarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStudentService")]
public interface IStudentService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudents", ReplyAction="http://tempuri.org/IStudentService/GetStudentsResponse")]
    SchoolRecords.WebService.Student[] GetStudents();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudents", ReplyAction="http://tempuri.org/IStudentService/GetStudentsResponse")]
    System.Threading.Tasks.Task<SchoolRecords.WebService.Student[]> GetStudentsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
    SchoolRecords.WebService.Student GetStudent(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
    System.Threading.Tasks.Task<SchoolRecords.WebService.Student> GetStudentAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/putStudent", ReplyAction="http://tempuri.org/IStudentService/putStudentResponse")]
    int putStudent(int id, SchoolRecords.WebService.Student val);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/putStudent", ReplyAction="http://tempuri.org/IStudentService/putStudentResponse")]
    System.Threading.Tasks.Task<int> putStudentAsync(int id, SchoolRecords.WebService.Student val);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/pushStudent", ReplyAction="http://tempuri.org/IStudentService/pushStudentResponse")]
    int pushStudent(SchoolRecords.WebService.Student val);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/pushStudent", ReplyAction="http://tempuri.org/IStudentService/pushStudentResponse")]
    System.Threading.Tasks.Task<int> pushStudentAsync(SchoolRecords.WebService.Student val);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/delStudent", ReplyAction="http://tempuri.org/IStudentService/delStudentResponse")]
    int delStudent(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/delStudent", ReplyAction="http://tempuri.org/IStudentService/delStudentResponse")]
    System.Threading.Tasks.Task<int> delStudentAsync(int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStudentServiceChannel : IStudentService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StudentServiceClient : System.ServiceModel.ClientBase<IStudentService>, IStudentService
{
    
    public StudentServiceClient()
    {
    }
    
    public StudentServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public SchoolRecords.WebService.Student[] GetStudents()
    {
        return base.Channel.GetStudents();
    }
    
    public System.Threading.Tasks.Task<SchoolRecords.WebService.Student[]> GetStudentsAsync()
    {
        return base.Channel.GetStudentsAsync();
    }
    
    public SchoolRecords.WebService.Student GetStudent(int id)
    {
        return base.Channel.GetStudent(id);
    }
    
    public System.Threading.Tasks.Task<SchoolRecords.WebService.Student> GetStudentAsync(int id)
    {
        return base.Channel.GetStudentAsync(id);
    }
    
    public int putStudent(int id, SchoolRecords.WebService.Student val)
    {
        return base.Channel.putStudent(id, val);
    }
    
    public System.Threading.Tasks.Task<int> putStudentAsync(int id, SchoolRecords.WebService.Student val)
    {
        return base.Channel.putStudentAsync(id, val);
    }
    
    public int pushStudent(SchoolRecords.WebService.Student val)
    {
        return base.Channel.pushStudent(val);
    }
    
    public System.Threading.Tasks.Task<int> pushStudentAsync(SchoolRecords.WebService.Student val)
    {
        return base.Channel.pushStudentAsync(val);
    }
    
    public int delStudent(int id)
    {
        return base.Channel.delStudent(id);
    }
    
    public System.Threading.Tasks.Task<int> delStudentAsync(int id)
    {
        return base.Channel.delStudentAsync(id);
    }
}
